export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_AUTHENTICATED= "SET_AUTHENTICATED";
export const LOAD_USER = "LOAD_USER";

export const QUESTION_LOADED = "QUESTION_LOADED";
export const SET_RESETMAIL = "SET_RESETMAIL";
export const RESPONSE_CONFIRMED = "REPONSE_CONFIRMED";
export const CLEAR_RESETDATA = "CLEAR_RESETDATA";